routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['categories'] = App\Category::where('nama_kategori', '!=', 'paket')->limit(6)->get();
    $data['services'] = App\Category::where('nama_kategori', 'paket')->first()->service;
    return view('welcome', $data);
});

//Admin Route
Route::prefix('admin')->group(function(){
    
    Auth::routes();
    
    Route::middleware('auth:web')->group(function() {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        //master
        Route::prefix('master')->group(function() {
            Route::resource('kategori', 'CategoryController');
            Route::resource('service', 'ServiceController');
            Route::resource('user', 'AdminController');
            Route::resource('gallery', 'GalleryController');
            Route::get('client', 'ClientController@index')->name('client.admin.index');
            Route::delete('client/{id}/delete', 'ClientController@destroy')->name('client.admin.destroy');
        });

        Route::prefix('transaksi')->group(function(){
            Route::resource('order', 'AdminOrderController');
            
            Route::delete('payment/{id}/delete/', 'PaymentController@delete')->name('payment.delete');
        });


        Route::get('laporan', function(){
            return redirect()->back();
        });
        
        Route::get('laporan/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::get('laporan/pesanan/print', 'LaporanController@printPesanan');

        Route::get('laporan/pembayaran', 'LaporanController@pembayaran')->name('laporan.pembayaran');
        Route::get('laporan/pembayaran/print', 'LaporanController@printPembayaran');
    
    });
});

Route::get('admin', function(){
    return redirect()->route('dashboard');
});

Route::get('admin/register', function(){
    return redirect()->route('login');
});



//Client Auth
Route::prefix('client')->group(function() {
    Route::get('login', 'ClientLoginController@showLoginForm')->name('client.loginform');
    Route::post('login', 'ClientLoginController@login')->name('client.login');
    Route::post('logout', 'ClientLoginController@logout')->name('client.logout');
    Route::get('register', 'ClientRegisterController@showRegisterForm')->name('client.registerform');
    Route::post('register', 'ClientRegisterController@register')->name('client.register');

    Route::middleware('auth-client:client')->group(function(){
        Route::get('profile', 'ClientController@profile')->name('client.profile');
        Route::get('profile/edit', 'ClientController@edit')->name('client.edit');
        Route::put('profile/edit', 'ClientController@update')->name('client.update');
    });
});

//Clint Order
Route::middleware('auth-client:client')->group(function() {
    Route::post('clients/{client}/place-order', 'OrderController@placeOrder')->name('client.order');
    Route::post('order/{order}/add', 'OrderController@addOrder')->name('order.add');
    Route::get('pesanan-saya', 'OrderController@showPesanan')->name('client.pesanan-saya');
    Route::get('pesanan-saya/{order}/detail', 'OrderController@detailPesanan')->name('client.pesanan.detail');
    Route::delete('clients/{order_id}/{service_id}/delete', 'OrderController@deleteService')->name('client.service.delete');
    //payment
    Route::get('pesanan-saya/{order}/bayar', 'PaymentController@formBayar')->name('client.pesanan.bayar');
    Route::post('clients/bayar', 'PaymentController@bayar')->name('client.pembayaran');
});


//Listing Product
Route::prefix('layanan')->group(function(){
    Route::get('/', 'ListingController@indexService')->name('layanan.index');
    Route::get('{slug}', 'ListingController@showService')->name('layanan.service');
    Route::get('{slug_kategory}/{slug_service}', 'ListingController@detailService')->name('layanan.detail');
});

//Gallery 
Route::get('gallery', 'ListingController@gallery');


Route::get('home', function(){
    return view('client.app');
});

resources/views/admin/app.blade.php
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@yield('title') - LaSari Bali</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="templates/assets/images/icon/favicon.ico">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/themify-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/metisMenu.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/slicknav.min.css') }}">
    
    <!-- Start datatable css -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.jqueryui.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="{{ asset('templates/assets/css/typography.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/default-css.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/styles.css') }}">
    <link rel="stylesheet" href="{{ asset('templates/assets/css/responsive.css') }}">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="{{ asset('magnific-popup/dist/magnific-popup.css') }}">

    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <!-- modernizr css -->
    <script src="{{ asset('templates/assets/js/vendor/modernizr-2.8.3.min.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('chartjs/Chart.min.css') }}">

    
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    @guest('web')
        @yield('content')
    @else
    <!-- page container area start -->
    <div class="page-container">
        @include('admin.sidebar')

        <!-- main content area start -->
        <div class="main-content">
            @include('admin.header')
            <!-- page title area start -->
            <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Dashboard</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{ url('admin') }}">Home</a></li>
                                @yield('breadcrumb')
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            <h4 class="user-name dropdown-toggle" data-toggle="dropdown">{{ ucwords(Auth::guard('web')->user()->name) }} <i class="fa fa-angle-down"></i></h4>
                            <div class="dropdown-menu">
                                <form action="{{ route('logout') }}" method="post">
                                    @csrf
                                    <button class="dropdown-item" type="submit">Logout</button>
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->

            <!-- MAIN CONTENT -->
            @yield('content')

        </div>
        <!-- main content area end -->

        @include('admin.footer')

    </div>
    @endguest
    <!-- offset area end -->
    <!-- jquery latest version -->
    <script src="{{ asset('templates/assets/js/vendor/jquery-2.2.4.min.js') }}"></script>
    <!-- bootstrap 4 js -->
    <script src="{{ asset('templates/assets/js/popper.min.js') }}"></script>
    <script src="{{ asset('templates/assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('templates/assets/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('templates/assets/js/metisMenu.min.js') }}"></script>
    <script src="{{ asset('templates/assets/js/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ asset('templates/assets/js/jquery.slicknav.min.js') }}"></script>

    <!-- Start datatable js -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
    <!-- others plugins -->
    <script src="{{ asset('templates/assets/js/plugins.js') }}"></script>
    <script src="{{ asset('templates/assets/js/scripts.js') }}"></script>
    <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('magnific-popup/dist/jquery.magnific-popup.js') }}"></script>
    <script src="{{ asset('chartjs/Chart.min.js') }}"></script>

    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'myeditor' );
    </script>

    @stack('scripts')
    
</body>

</html>

resources/views/admin/dashboard.blade.php
@extends('admin.app')

@section('title')
Dashboard
@endsection

@section('breadcrumb')

<li><span>Dashboard</span></li>

@endsection

@section('content')
<div class="main-content-inner">
    <div class="row mt-5 mb-4">
        <div class="col-md-4">
            <div class="seo-fact sbg1">
                <div class="p-4 d-flex justify-content-between align-items-center">
                    <div class="seofct-icon"><i class="ti-briefcase"></i> Total Layanan</div>
                    <h2>{{ $total_service }}</h2>
                </div>                   
            </div>
        </div>
        <div class="col-md-4">
            <div class="seo-fact sbg2">
                <div class="p-4 d-flex justify-content-between align-items-center">
                    <div class="seofct-icon"><i class="ti-shopping-cart"></i> Total Pesanan</div>
                    <h2>{{ $total_order }}</h2>
                </div>                   
            </div>
        </div>
        <div class="col-md-4">
            <div class="seo-fact sbg4">
                <div class="p-4 d-flex justify-content-between align-items-center">
                    <div class="seofct-icon"><i class="ti-user"></i> Total Client</div>
                    <h2>{{ $total_client }}</h2>
                </div>                   
            </div>
        </div>
    </div>
    <div class="row mt-5 mb-4">
        <div class="col-md-4">
            <div class="single-report">
                <div class="s-report-inner pr--20 pt--30 mb-3">
                    <div class="icon"><i class="fa fa-bars"></i></div>
                    <div class="s-report-title d-flex justify-content-between">
                        <h4 class="header-title mb-0">Acara Selesai</h4>                        
                    </div>
                    <div class="d-flex justify-content-between pb-2">
                        <h2 style="font-size:30px">{{ $selesai }}</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="single-report">
                <div class="s-report-inner pr--20 pt--30 mb-3">
                    <div class="icon"><i class="fa fa-bars"></i></div>
                    <div class="s-report-title d-flex justify-content-between">
                        <h4 class="header-title mb-0">Pesanan On Progress</h4>                        
                    </div>
                    <div class="d-flex justify-content-between pb-2">
                        <h2 style="font-size:30px">{{ $progress }}</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="single-report">
                <div class="s-report-inner pr--20 pt--30 mb-3">
                    <div class="icon"><i class="fa fa-bars"></i></div>
                    <div class="s-report-title d-flex justify-content-between">
                        <h4 class="header-title mb-0">Pesanan Belum Dibayar</h4>                        
                    </div>
                    <div class="d-flex justify-content-between pb-2">
                        <h2 style="font-size:30px">{{ $belum_bayar }}</h2>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card">
                <div class="cart-body">
                    <canvas id="chart1" width="400" height="400"></canvas>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="cart-body">
                    <canvas id="chart2" width="400" height="400"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 ">
            
            @include('admin.flash')

            <div class="card">                
                <div class="card-body">
                    <h4 class="header-title">Selamat Datang</h4>
                    
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, neque sit. Doloremque nobis facere necessitatibus deleniti natus autem dicta, praesentium impedit obcaecati sunt laboriosam incidunt alias aut veritatis harum commodi!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, neque sit. Doloremque nobis facere necessitatibus deleniti natus autem dicta, praesentium impedit obcaecati sunt laboriosam incidunt alias aut veritatis harum commodi!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, neque sit. Doloremque nobis facere necessitatibus deleniti natus autem dicta, praesentium impedit obcaecati sunt laboriosam incidunt alias aut veritatis harum commodi!</p>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

@push('scripts')
<script>
(function($) {
$.get('/api/chart', function(response) {
    let data = response.data;

    let services = data.services.map(function(item) {
        return item.service
    });
    let services_count = data.services.map(function(item) {
        return item.count;
    });

    let years = data.orders.map(function(item) {
        return item.year;
    });
    let counts = data.orders.map(function(item) {
        return item.count
    })

    var ctx = document.getElementById('chart1');
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: services,
        datasets: [{
            label: '# Layanan Terlaris',
            data: services_count,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

    // Dummy data
    // Uncomment this to see chart looks like
    // years = [2015, 2016, 2017, 2018, 2019];
    // counts = [20, 50, 12, 15, 20];

    var ctx2 = document.getElementById('chart2');
    var myChart2 = new Chart(ctx2, {
    type: 'line',
    data: {
        labels: years,
        datasets: [{
            label: '# Penjualan 5 Tahun Terakhir',
            data: counts,
            backgroundColor: 'rgba(255, 99, 132, 0.2)',
            borderColor: 'rgba(255, 99, 132, 1)',
            borderWidth: 1,
            fill: false
        }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

});
})(jQuery)
</script>    
@endpush

resources/views/admin/flash.blade.php
<div class="alert-dismiss">
    @if(session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session()->get('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span class="fa fa-times"></span>
        </button>
    </div>
    @endif

    @if(session()->has('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ session()->get('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span class="fa fa-times"></span>
        </button>
    </div>
    @endif

    @if(session()->has('warning'))
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ session()->get('warning') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span class="fa fa-times"></span>
        </button>
    </div>
    @endif
</div>

<!-- FORM ERROR VALIDATION -->
@if($errors->any())
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
                
            </div>
        </div>
    </div>
@endif

resources/views/admin/footer.blade.php
        <footer>
            <div class="footer-area">
                <p>© Copyright 2019. All right reserved. by <a href="#">LaSari Bali</a>.</p>
            </div>
        </footer>

resources/views/admin/header.blade.php
            <!-- header area start -->
            <div class="header-area">
                <div class="row align-items-center">
                    <!-- nav and search button -->
                    <div class="col-md-6 col-sm-8 clearfix">
                        <div class="nav-btn pull-left">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                        
                    </div>
                     <!-- profile info & task notification -->
                     <div class="col-md-6 col-sm-4 clearfix">
                        <ul class="notification-area pull-right">
                            <li id="full-view"><i class="ti-fullscreen"></i></li>
                            <li id="full-view-exit"><i class="ti-zoom-out"></i></li>
                         
                        </ul>
                    </div>
                </div>
            </div>
            <!-- header area end -->

resources/views/admin/sidebar.blade.php
        <!-- sidebar menu area start -->
        <div class="sidebar-menu">
            <div class="sidebar-header">
                <div class="logo brand">
                    <a href="{{ url('admin') }}">LaSari Bali</a>
                </div>
            </div>
            <div class="main-menu">
                <div class="menu-inner">
                    <nav>
                        <ul class="metismenu" id="menu">
                            <li class="{{ hasPrefix('master') ? 'active':'' }}">
                            <a href="javascript:void(0)" aria-expanded="true"><i class="ti-dashboard"></i><span>Master</span></a>
                                <ul class="collapse">
                                    <li class="{{ hasPrefix('kategori') ? 'active':'' }}"><a href="{{ route('kategori.index') }}">Kategori</a></li>
                                    <li class="{{ hasPrefix('service') ? 'active':'' }}"><a href="{{ route('service.index') }}">Service</a></li>
                                    <li class="{{ hasPrefix('gallery') ? 'active':'' }}"><a href="{{ route('gallery.index') }}">Gallery</a></li>
                                    <li class="{{ hasPrefix('client') ? 'active':'' }}"><a href="{{ route('client.admin.index') }}">Client</a></li>                                    
                                    <li class="{{ hasPrefix('user') ? 'active':'' }}"><a href="{{ route('user.index') }}">Admin</a></li>
                                </ul>
                            </li>
                            <li class="{{ hasPrefix('transaksi') ? 'active':'' }}">
                                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-money"></i><span>Transaksi</span></a>
                                <ul class="collapse">
                                    <li class="{{ hasPrefix('order') ? 'active':'' }}"><a href="{{ route('order.index') }}">Pesanan</a></li>
                                </ul>
                            </li>
                            <li class="{{ hasPrefix('laporan') ? 'active':'' }}">
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-file"></i><span>Laporan</span></a>
                                <ul class="collapse">
                                    <li class="{{ hasPrefix('pesanan') ? 'active':'' }}"><a href="{{ route('laporan.pesanan') }}">Pesanan</a></li>
                                    <li class="{{ hasPrefix('pembayaran') ? 'active':'' }}"><a href="{{ route('laporan.pembayaran') }}">Pembayaran</a></li>
                                </ul>
                            </li>
                        </ul>
                      
                            
                    
                    </nav>
                </div>
            </div>
        </div>
        <!-- sidebar menu area end -->