routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['categories'] = App\Category::where('nama_kategori', '!=', 'paket')->limit(6)->get();
    $data['services'] = App\Category::where('nama_kategori', 'paket')->first()->service;
    return view('welcome', $data);
});

//Admin Route
Route::prefix('admin')->group(function(){
    
    Auth::routes();
    
    Route::middleware('auth:web')->group(function() {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        //master
        Route::prefix('master')->group(function() {
            Route::resource('kategori', 'CategoryController');
            Route::resource('service', 'ServiceController');
            Route::resource('user', 'AdminController');
            Route::resource('gallery', 'GalleryController');
            Route::get('client', 'ClientController@index')->name('client.admin.index');
            Route::delete('client/{id}/delete', 'ClientController@destroy')->name('client.admin.destroy');
        });

        Route::prefix('transaksi')->group(function(){
            Route::resource('order', 'AdminOrderController');
            
            Route::delete('payment/{id}/delete/', 'PaymentController@delete')->name('payment.delete');
        });


        Route::get('laporan', function(){
            return redirect()->back();
        });
        
        Route::get('laporan/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::get('laporan/pesanan/print', 'LaporanController@printPesanan');

        Route::get('laporan/pembayaran', 'LaporanController@pembayaran')->name('laporan.pembayaran');
        Route::get('laporan/pembayaran/print', 'LaporanController@printPembayaran');
    
    });
});

Route::get('admin', function(){
    return redirect()->route('dashboard');
});

Route::get('admin/register', function(){
    return redirect()->route('login');
});



//Client Auth
Route::prefix('client')->group(function() {
    Route::get('login', 'ClientLoginController@showLoginForm')->name('client.loginform');
    Route::post('login', 'ClientLoginController@login')->name('client.login');
    Route::post('logout', 'ClientLoginController@logout')->name('client.logout');
    Route::get('register', 'ClientRegisterController@showRegisterForm')->name('client.registerform');
    Route::post('register', 'ClientRegisterController@register')->name('client.register');

    Route::middleware('auth-client:client')->group(function(){
        Route::get('profile', 'ClientController@profile')->name('client.profile');
        Route::get('profile/edit', 'ClientController@edit')->name('client.edit');
        Route::put('profile/edit', 'ClientController@update')->name('client.update');
    });
});

//Clint Order
Route::middleware('auth-client:client')->group(function() {
    Route::post('clients/{client}/place-order', 'OrderController@placeOrder')->name('client.order');
    Route::post('order/{order}/add', 'OrderController@addOrder')->name('order.add');
    Route::get('pesanan-saya', 'OrderController@showPesanan')->name('client.pesanan-saya');
    Route::get('pesanan-saya/{order}/detail', 'OrderController@detailPesanan')->name('client.pesanan.detail');
    Route::delete('clients/{order_id}/{service_id}/delete', 'OrderController@deleteService')->name('client.service.delete');
    //payment
    Route::get('pesanan-saya/{order}/bayar', 'PaymentController@formBayar')->name('client.pesanan.bayar');
    Route::post('clients/bayar', 'PaymentController@bayar')->name('client.pembayaran');
});


//Listing Product
Route::prefix('layanan')->group(function(){
    Route::get('/', 'ListingController@indexService')->name('layanan.index');
    Route::get('{slug}', 'ListingController@showService')->name('layanan.service');
    Route::get('{slug_kategory}/{slug_service}', 'ListingController@detailService')->name('layanan.detail');
});

//Gallery 
Route::get('gallery', 'ListingController@gallery');


Route::get('home', function(){
    return view('client.app');
});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = [
        'name',
        'foto'
    ];
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Gallery;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.gallery.index')->with('galleries', Gallery::paginate(6));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'foto' => 'required'
        ]);

        $store_image = $request->file('foto')->store('gallery');
        if($store_image) {
            $file_name = $request->foto->hashName();
            resizeImageGallery($file_name);
        }

        Gallery::create([
            'name' => $request->name,
            'foto' => $file_name
        ]);

        return redirect()->back()->with('success', 'Berhasil menambahkan data gallery');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.gallery.edit')->with('gallery', Gallery::findOrFail($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $gallery = Gallery::findOrFail($id);
        $file_name = $gallery->foto;

        if($request->hasFile('foto') == true){
            unlink('storage/gallery/'.$file_name);
            unlink('storage/gallery/small/'.$file_name);
            $request->file('foto')->store('gallery');
            $file_name = $request->foto->hashName();
            resizeImageGallery($file_name);
        }

        $gallery->update([
            'name' => $request->name,
            'foto' => $file_name
        ]);

        return redirect()->route('gallery.index')->with('success', 'Berhasil mengedit data gallery');




    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gallery = Gallery::find($id);
        unlink('storage/gallery/'.$gallery->foto);
        unlink('storage/gallery/small/'.$gallery->foto);
        $gallery->delete();

        return redirect()->back()->with('success', 'Berhasil menghapus data gallery');
    }
}

resources/views/admin/gallery/edit.blade.php
@extends('admin.app')

@section('title')
Edit Gallery
@endsection

@section('breadcrumb')

<li><a href="{{ route('gallery.index') }}">Gallery</a></li>
<li><span>Edit</span></li>

@endsection

@section('content')
<div class="main-content-inner">
     
    <div class="row">
        <div class="col-6 mt-5">
            
            @include('admin.flash')

            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Edit Gallery</h4>

                    <div id="accordion4" class="according accordion-s3 gradiant-bg col-md-12 my-form">
                        <div class="card">
                            <div id="accordion41" class="collapse show" data-parent="#accordion4" style="">
                                <div class="card-body">
                                    <form action="{{ route('gallery.update', ['id' => $gallery->id]) }}" method="post" enctype="multipart/form-data">
                                        @csrf
                                        @method('put')
                                        <div class="form-group">
                                            <label for="name" class="col-form-label">Nama Foto</label>
                                            <input class="form-control" type="text" value="{{ $gallery->name }}" id="name" name="name">
                                        </div>
                                        <div class="form-group">
                                            <img src="{{ asset('storage/gallery/small/'. $gallery->foto ) }}" alt="{{ $gallery->foto }}" width="100%"> <br>
                                            <label for="deskripsi" class="col-form-label">Foto</label>
                                            <input type="file" class="form-control" name="foto">
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-block btn-success" value="Simpan">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/gallery/index.blade.php
@extends('admin.app')

@section('title')
Gallery
@endsection

@section('breadcrumb')

<li><span>Gallery</span></li>

@endsection

@section('content')
<div class="main-content-inner">
     
    <div class="row">
        <div class="col-12 mt-5">
            
            @include('admin.flash')

            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Data Gallery</h4>

                    <a id="addGallery" data-toggle="collapse" href="#accordion41" aria-expanded="true" class="btn btn-info btn-sm">Tambah Gallery</a>
                    <!-- form input -->
                    <div id="accordion4" class="according accordion-s3 gradiant-bg col-md-6 my-form">
                        <div class="card">
                            <div id="accordion41" class="collapse" data-parent="#accordion4" style="">
                                <div class="card-body">
                                    <form action="{{ route('gallery.store') }}" method="post" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group">
                                            <label for="name" class="col-form-label">Nama Foto</label>
                                            <input class="form-control" type="text" value="{{ old('name') }}" id="name" name="name">
                                        </div>
                                      
                                        <div class="form-group">
                                            <label for="deskripsi" class="col-form-label">Foto</label>
                                            <input type="file" class="form-control" name="foto">
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-block btn-success" value="Simpan">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br>
                    <div class="inner-content">
                        <div class="row">
                            
                            @foreach($galleries as $row)
                            <div class="col-md-4 mb-4 bordered">
                                <h5 class="mb-3">{{ $row->name }}</h5>
                                
                               
                                <div class="popup-gallery">
                                    <a href="{{ asset('storage/gallery/'. $row->foto ) }}" title="{{ $row->name }}"><img src="{{ asset('storage/gallery/small/'. $row->foto ) }}"></a>
                                </div>
                                <div class="button-image">
                                    <form action="{{ route('gallery.destroy', ['id' => $row->id]) }}" method="post">
                                        <ul class="d-flex justify-content-center">
                                            <li class="mr-3"><a href="{{ route('gallery.edit', ['id' => $row->id ]) }}" class="text-dark"><i class="fa fa-edit"></i> Edit </a></li>
                                            @csrf
                                            @method('delete')
                                            <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="ti-trash"></i> Hapus</button></li>
                                        </ul>
                                    </form>
                                </div>                                                                                 
                                
                            </div>
                            @endforeach
                        </div>

                        <div class="row">
                            <div class="col-md-12">                            
                                @if ($galleries instanceof \Illuminate\Pagination\LengthAwarePaginator )
                                    {{ $galleries->links() }}
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>

(function($) {

function toggleContent(){
    if($('.collapse').hasClass('show')){
        $('.inner-content').css('display', 'block');
    } else {
        $('.inner-content').css('display', 'none');
    }
}

$('#addGallery').on('click', function(e) {
    e.preventDefault();

    toggleContent();
});

$(document).ready(function() {
	$('.popup-gallery').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		mainClass: 'mfp-img-mobile',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
			titleSrc: function(item) {
				return item.el.attr('title') + '<small>by LaSari Bali Weeding and Event</small>';
			}
		}
	});
});

})(jQuery)
</script>
@endpush