routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['categories'] = App\Category::where('nama_kategori', '!=', 'paket')->limit(6)->get();
    $data['services'] = App\Category::where('nama_kategori', 'paket')->first()->service;
    return view('welcome', $data);
});

//Admin Route
Route::prefix('admin')->group(function(){
    
    Auth::routes();
    
    Route::middleware('auth:web')->group(function() {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        //master
        Route::prefix('master')->group(function() {
            Route::resource('kategori', 'CategoryController');
            Route::resource('service', 'ServiceController');
            Route::resource('user', 'AdminController');
            Route::resource('gallery', 'GalleryController');
            Route::get('client', 'ClientController@index')->name('client.admin.index');
            Route::delete('client/{id}/delete', 'ClientController@destroy')->name('client.admin.destroy');
        });

        Route::prefix('transaksi')->group(function(){
            Route::resource('order', 'AdminOrderController');
            
            Route::delete('payment/{id}/delete/', 'PaymentController@delete')->name('payment.delete');
        });


        Route::get('laporan', function(){
            return redirect()->back();
        });
        
        Route::get('laporan/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::get('laporan/pesanan/print', 'LaporanController@printPesanan');

        Route::get('laporan/pembayaran', 'LaporanController@pembayaran')->name('laporan.pembayaran');
        Route::get('laporan/pembayaran/print', 'LaporanController@printPembayaran');
    
    });
});

Route::get('admin', function(){
    return redirect()->route('dashboard');
});

Route::get('admin/register', function(){
    return redirect()->route('login');
});



//Client Auth
Route::prefix('client')->group(function() {
    Route::get('login', 'ClientLoginController@showLoginForm')->name('client.loginform');
    Route::post('login', 'ClientLoginController@login')->name('client.login');
    Route::post('logout', 'ClientLoginController@logout')->name('client.logout');
    Route::get('register', 'ClientRegisterController@showRegisterForm')->name('client.registerform');
    Route::post('register', 'ClientRegisterController@register')->name('client.register');

    Route::middleware('auth-client:client')->group(function(){
        Route::get('profile', 'ClientController@profile')->name('client.profile');
        Route::get('profile/edit', 'ClientController@edit')->name('client.edit');
        Route::put('profile/edit', 'ClientController@update')->name('client.update');
    });
});

//Clint Order
Route::middleware('auth-client:client')->group(function() {
    Route::post('clients/{client}/place-order', 'OrderController@placeOrder')->name('client.order');
    Route::post('order/{order}/add', 'OrderController@addOrder')->name('order.add');
    Route::get('pesanan-saya', 'OrderController@showPesanan')->name('client.pesanan-saya');
    Route::get('pesanan-saya/{order}/detail', 'OrderController@detailPesanan')->name('client.pesanan.detail');
    Route::delete('clients/{order_id}/{service_id}/delete', 'OrderController@deleteService')->name('client.service.delete');
    //payment
    Route::get('pesanan-saya/{order}/bayar', 'PaymentController@formBayar')->name('client.pesanan.bayar');
    Route::post('clients/bayar', 'PaymentController@bayar')->name('client.pembayaran');
});


//Listing Product
Route::prefix('layanan')->group(function(){
    Route::get('/', 'ListingController@indexService')->name('layanan.index');
    Route::get('{slug}', 'ListingController@showService')->name('layanan.service');
    Route::get('{slug_kategory}/{slug_service}', 'ListingController@detailService')->name('layanan.detail');
});

//Gallery 
Route::get('gallery', 'ListingController@gallery');


Route::get('home', function(){
    return view('client.app');
});

app/Orders.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Orders extends Model
{
    protected $fillable = [
        'client_id',
        'nomor_pesanan',
        'tgl_pesanan',
        'nama_acara',
        'tgl_acara',
        'alamat_acara',
        'total_harga',
        'catatan',
        'status_pesanan'
    ];

    protected $dates = [
        'tgl_acara'
    ];

    public $statusText = [
        '0' => 'Menunggu Pembayaran',
        '1' => 'Menunggu Konfirmasi Pembayaran',
        '2' => 'Pembayaran Dikonfirmasi',
        '3' => 'Pesanan Siap Untuk Acara',
        '4' => 'Acara Selesai',
        '5' => 'Pesanan Dibatalkan'
    ];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function details()
    {
        return $this->hasMany(OrderDetail::class, 'order_id');
    }

    public function getStatusText() {
        return $this->statusText[$this->status_pesanan];
    }

    public function payments() {
        return $this->hasMany(Payment::class, 'order_id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Client;
use App\Service;
use App\User;
use App\Orders;
use App\Http\Requests\OrderRequest;
use App\Notifications\ClientOrderNotification;
use App\Notifications\AdminOrderNotification;
use Carbon\Carbon;
use Auth;

class OrderController extends Controller
{
    public function placeOrder(OrderRequest $request, Client $client)
    {
        $data = $request->all();
        
        $sameDate = Orders::where('tgl_acara', $data['tgl_acara'])->count();
        
        if ($sameDate >= 3) {
            return redirect()->back()->with('error', 'Tidak bisa membuat order pada tanggal tersebut, coba pada tanggal lain!');
        }
        
        $data['total_harga'] = Service::find($data['service_id'])->harga;
    
        $order = $client->orders()->create($data);
        $order->details()->create([
            'service_id' => $data['service_id']
        ]);

        $client->notify(new ClientOrderNotification($client, $order));
        
        $admin = User::where('email', env('DEFAULT_ADMIN_EMAIL', ''))->first();
        $admin->notify(new AdminOrderNotification($order));

        return redirect()->route('layanan.index')->with('success', 'Pesanan berhasil dibuat');
    }

    public function addOrder(Request $request, Orders $order)
    {
        $check = $order->details()->where('service_id', $request->get('service_id'))->first();
        // if($check){
        //     return redirect()->back()->with('error', 'Tidak dapat memesan service yang sama');
        // }
        $details = $order->details()->create([
            'service_id' => $request->get('service_id')
        ]);

        $service = Service::find($request->get('service_id'));
        $order->total_harga += $service->harga;
        $order->save();

        return redirect()->back()->with('success', '1 Order berhasil ditambahkan');
    }

    public function showPesanan(){
        $client = Auth::guard('client')->user();
        $data['orders'] = Orders::where('client_id', $client->id)->get();

        return view('order.daftar_pesanan', $data);        
    }

    public function detailPesanan($no_order){
        $client = Auth::guard('client')->user();
        $order = Orders::where('client_id', $client->id)
                        ->where('nomor_pesanan', $no_order)
                        ->first();
        if($order == null){
            return redirect()->back()->with('error', 'Data order tidak ada.');
        }

        $data['order'] = $order;
        
        return view('order.detail_pesanan', $data);
    }

    public function deleteService($order_id, $service_id){
        $order = Orders::find($order_id);
        if($order->status_pesanan == 0){
            $sumDetail = $order->details->count();
            if($sumDetail != 1){
                $detail = $order->details->where('service_id', $service_id)->first();
                
                $order->update([
                    'total_harga' => $order->total_harga - $detail->service->harga
                ]);

                $detail->delete();
                
                return redirect()->back()->with('success', 'Berhasil menghapus data layanan');
            } else {
                return redirect()->back()->with('error', 'Gagal menghapus layanan karena hanya ada 1 pesanan');
            }
            
        } else {
            return redirect()->back()->with('error', 'Gagal menghapus layanan karena anda telah melakukan pembayaran');
        }

    }

    
}

resources/views/admin/order/index.blade.php
@extends('admin.app')

@section('title')
Data Order 
@endsection

@section('breadcrumb')

<li><span>Order</span></li>

@endsection

@section('content')
<div class="main-content-inner">
     
    <div class="row">
        <div class="col-12 mt-5">
            
            @include('admin.flash')

            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Data Order</h4>

                    <br>
                    <div class="data-tables inner-content">
                        <table id="dataTable" class="text-center">
                            <thead class="bg-light text-capitalize">
                                <tr>
                                    <th>No</th>
                                    <th>Nomor Order</th>
                                    <th>Nama Client</th>
                                    <th>Status</th>
                                    <th>Total Harga</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               @foreach($orders as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->nomor_pesanan }}</td>
                                        <td>{{ $row->client->nama_client }}</td>
                                        <td><span class="status-p {{ orderStatusColor($row->status_pesanan) }}">{{ $row->getStatusText() }}</span></td>
                                        <td>{{ 'Rp. '.number_format($row->total_harga) }}</td>
                                        <td>
                                            <a href="{{ route('order.show', $row->id) }}" class="btn btn-success">Detail</a>
                                        </td>       
                                    </tr>
                               @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>

(function($) {



})(jQuery)
</script>
@endpush

resources/views/admin/order/show.blade.php
@extends('admin.app')

@section('title')
Detail Order 
@endsection

@section('breadcrumb')

<li><span>Order</span></li>

@endsection

@section('content')
<div class="main-content-inner">
    <div class="row">
        <div class="col-md-12 mt-5 mb-5">
            @include('client.flash')
            <div class="card">
                <div class="card-body">
                    <h3 class="">Detail Pesanan</h3>
                    <br>
                    <div class="row">
                        <div class="col-md-8 mb-5">
                            <table class="table">
                                <tr>
                                    <td>Pemesan</td>
                                    <td>:</td>
                                    <td>{{ $order->client->nama_client }}</td>
                                </tr>
                                <tr>
                                    <td>Nomor Order</td>
                                    <td>:</td>
                                    <td>{{ $order->nomor_pesanan }}</td>
                                </tr>
                                <tr>
                                    <td>Nama Acara</td>
                                    <td>:</td>
                                    <td>{{ $order->nama_acara }}</td>
                                </tr>
                                <tr>
                                    <td>Tanggal Acara</td>
                                    <td>:</td>
                                    <td>{{ $order->tgl_acara->format('d M Y') }}</td>
                                </tr>
                                <tr>
                                    <td>Alamat Acara</td>
                                    <td>:</td>
                                    <td>{{ $order->alamat_acara }}</td>
                                </tr>
                                <tr>
                                    <td>Total Harga</td>
                                    <td>:</td>
                                    <td>{{ 'Rp. '.number_format($order->total_harga) }}</td>
                                </tr>
                                <tr>
                                    <td>Catatan </td>
                                    <td>:</td>
                                    <td>{{ $order->catatan }}</td>
                                </tr>
                            </table>

                            <h4>Data Layanan</h4>
                            <br>
                            <div class="single-table">
                                <div class="table-responsive">
                                    <table class="table text-center">
                                        <thead class="text-uppercase bg-dark">
                                            <tr class="text-white">
                                                <th scope="col">No</th>
                                                <th scope="col">Kode</th>
                                                <th scope="col">Nama</th>
                                                <th scope="col">Kategori</th>
                                                <th scope="col">Harga</th>
                                              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse($order->details as $service)
                                                @if($service->service == null) 
                                                <tr>
                                                    <td colspan="6">Data Service Telah diHapus</td>
                                                </tr>
                                                @else
                                                <tr>
                                                    <th scope="row">{{ $loop->iteration }}</th>
                                                    <td>{{ $service->service->kode_service }}</td>
                                                    <td>{{ $service->service->nama_service }}</td>
                                                    <td>{{ $service->service->category->nama_kategori }}</td>
                                                    <td>{{ 'Rp. '.number_format($service->service->harga) }}</td>
                                                
                                                </tr>
                                                @endif
                                                
                                            @empty
                                            <tr>
                                                <td colspan="6" class="text-center">Client ini tidak memiliki service</td>
                                            </tr>

                                            @endforelse
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <br>

                            <h4>Data Pembayaran</h4>
                            <br>
                            <div class="single-table">
                                <div class="table-responsive">
                                    <table class="table text-center">
                                        <thead class="text-uppercase bg-dark">
                                            <tr class="text-white">
                                                <th scope="col">No</th>
                                                <th scope="col">Tanggal</th>
                                                <th scope="col">Nominal</th>
                                                <th scope="col">Status</th>
                                                <th scope="col">Bukti</th>
                                                <th scope="col">Hapus</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse($order->payments as $payment)

                                            <tr>
                                                <th scope="row">{{ $loop->iteration }}</th>
                                                <td>{{ $payment->tgl_pembayaran->format('d M Y') }}</td>
                                                <td>{{ 'Rp. '.number_format($payment->nominal_pembayaran) }}</td>
                                                <td>{{ $payment->getStatusText() }}</td>
                                                <td class="bukti-transfer">
                                                    <a href="{{ asset('storage/bukti_transfer/'. $payment->bukti_transfer ) }}" title="{{ $payment->bukti_transfer }}"><img src="{{ asset('storage/bukti_transfer/'. $payment->bukti_transfer ) }}"></a>
                                                </td>
                                                <td>
                                                    <form action="{{ route('payment.delete', ['payment_id' => $payment->id]) }}" method="post">
                                                        @csrf 
                                                        @method('delete')
                                                        <button type="submit" onclick="return confirm('Yakin hapus layanan?')">
                                                            <i class="ti-trash"></i>
                                                        </button>

                                                    </form>    
                                                </td>
                                            </tr>

                                            @empty
                                            <tr>
                                                <td colspan="6" class="text-center">Client ini belum melakukan pembayaran</td>
                                            </tr>

                                            @endforelse
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">                        
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <h4 class="header-title">Update Status Pesanan</h4>
                                    <form action="{{ route('order.update', $order->id) }}" class="form form-inline" method="post">
                                        @csrf 
                                        @method('put')
                                        <div class="form-group">
                                            <select name="status_pesanan" id="status" class="form-control" style="height: 50px">
                                                @for ($i = 0; $i < 6; $i++)
                                                    <option value="{{ $i }}" {{ ($order->status_pesanan == $i) ? 'selected':'' }}>{{ statusText($i) }}</option>
                                                @endfor
                                            </select>
                                        </div>
                                        <div class="form-group mt-2">
                                            <button type="submit" class="btn btn-default">Simpan</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-12">
                                    <h4 class="header-title">Status Pesanan</h4>
                                    <div class="slimScrollDiv">
                                        <div class="timeline-area">
                                            @if($order->status_pesanan == 5)
                                                <div class="timeline-task">
                                                        
                                                    <div class="icon bg-danger">
                                                        <i class="fa fa-times"></i>
                                                        
                                                    </div>
                                                    <div class="tm-title">Pesanan Dibatalkan</div>
                                                </div>
                                            @else

                                                @for ($i = 0; $i < 5; $i++)
                                                    <div class="timeline-task">
                                                        @if ($order->status_pesanan > $i)
                                                            <div class="icon bg-success">
                                                        @elseif($order->status_pesanan == $i)
                                                            <div class="icon bg-warning">
                                                        @else
                                                            <div class="icon bg-secondary">
                                                        @endif
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <div class="tm-title">
                                                            <h4>{{ $order->statusText[$i] }}</h4>                                                
                                                        </div>
                                                    </div>
                                                @endfor
                                            @endif
                                        </div>
                                    </div>

                                </div>
                                
                            </div>
                        
                   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@push('scripts')
<script>

$(document).ready(function() {
	$('.bukti-transfer').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		mainClass: 'mfp-img-mobile',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
			titleSrc: function(item) {
				return item.el.attr('title') + '<small>Bukti Transfer</small>';
			}
		}
	});
});

</script>
@endpush